//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_App_V1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Human_ResourcesEntities : DbContext
    {
        public Human_ResourcesEntities()
            : base("name=Human_ResourcesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Claim_Ruling_Type> Claim_Ruling_Type { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FMLA_Absence_Tracking_Type> FMLA_Absence_Tracking_Type { get; set; }
        public virtual DbSet<FMLA_Leave_Type> FMLA_Leave_Type { get; set; }
        public virtual DbSet<FMLA_PLA_Tracking> FMLA_PLA_Tracking { get; set; }
        public virtual DbSet<Injury_Leave> Injury_Leave { get; set; }
        public virtual DbSet<TTD_Type> TTD_Type { get; set; }
        public virtual DbSet<WC_Type> WC_Type { get; set; }
        public virtual DbSet<Workers_Compensation> Workers_Compensation { get; set; }
    }
}
